version 9.3.20

diff --git a/src/swipl-devel/scripts/configure b/src/swipl-devel/scripts/configure
--- a/src/swipl-devel/scripts/configure
+++ b/src/swipl-devel/scripts/configure
@@ -15,6 +15,7 @@ export CC=
 export CXX=
 opts=
 cmake=cmake
+os=any
 
 config=$(basename $(pwd))
 
@@ -40,6 +41,33 @@ case $config in
     ;;
 esac
 
+# wasm
+# termux
+#
+# Build for specific targets
+
+case $config in
+    *wasm*)
+        os=wasm
+	WASM_HOME=${WASM_HOME-$HOME/wasm}
+	source $WASM_HOME/emsdk/emsdk_env.sh
+	TOOLCHAIN=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
+	[ -f $TOOLCHAIN ] || echo "Could not find emscripten toolchain"
+	cmake="emcmake cmake"
+	build_type=Release
+	LDFLAGS+=" -s STACK_SIZE=1048576"
+	opts+=" -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN"
+	opts+=" -DCMAKE_FIND_ROOT_PATH=$WASM_HOME"
+	opts+=" -DUSE_GMP=OFF"
+	opts+=" -DINSTALL_DOCUMENTATION=OFF"
+	;;
+    *termux*)
+	opts+=" -DPOSIX_SHELL=${PREFIX}/bin/sh"
+	opts+=" -DSWIPL_TMP_DIR=${PREFIX}/tmp"
+	opts+=" -DSYSTEM_CACERT_FILENAME=${PREFIX}/etc/tls/cert.pem"
+	;;
+esac
+
 # nogmp
 # libbf
 #
@@ -61,12 +89,25 @@ case $config in
     ;;
 esac
 
+# engines
+#
+# Include engine support, also in single threaded versions.
+
+case $config in
+  *engines*)
+    opts+=" -DENGINES=ON"
+    ;;
+esac
+
 # vmif
 #
 # Implement VMI instructions as functions.  Slower on GCC, about
 # equal for Clang (and WASM) and much faster for MSVC
 
 case $config in
+  *novmif*)
+    opts+=" -DVMI_FUNCTIONS=OFF"
+    ;;
   *vmif*)
     opts+=" -DVMI_FUNCTIONS=ON"
     ;;
@@ -171,6 +212,9 @@ case $config in
     build_type=PGO
     ;;
   *debug*)
+    if [ $os == wasm ]; then
+        LDFLAGS+=" -sASSERTIONS"
+    fi
     build_type=Debug
     ;;
   *asan*)
@@ -180,32 +224,6 @@ case $config in
     build_type=Sanitize
     opts+=" -DSANITIZE=undefined"
     ;;
-esac
-
-# wasm
-# termux
-#
-# Build for specific targets
-
-case $config in
-    *wasm*)
-	WASM_HOME=$HOME/wasm
-	source $WASM_HOME/emsdk/emsdk_env.sh
-	TOOLCHAIN=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
-	[ -f $TOOLCHAIN ] || echo "Could not find emscripten toolchain"
-	cmake="emcmake cmake"
-	build_type=Release
-	LDFLAGS+=" -s STACK_SIZE=1048576"
-	opts+=" -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN"
-	opts+=" -DCMAKE_FIND_ROOT_PATH=$HOME/wasm"
-	opts+=" -DUSE_GMP=OFF"
-	opts+=" -DINSTALL_DOCUMENTATION=OFF"
-	;;
-    *termux*)
-	opts+=" -DPOSIX_SHELL=${PREFIX}/bin/sh"
-	opts+=" -DSWIPL_TMP_DIR=${PREFIX}/tmp"
-	opts+=" -DSYSTEM_CACERT_FILENAME=${PREFIX}/etc/tls/cert.pem"
-	;;
 esac
 
 function confirm ()
@@ -257,5 +275,10 @@ chmod +x configure
 [ -z "$CXX" ]     || echo "export CXX=$CXX"               >> .envrc
 [ -z "$CFLAGS" ]  || echo "export CFLAGS="'"'$CFLAGS'"'   >> .envrc
 [ -z "$LDFLAGS" ] || echo "export LDFLAGS="'"'$LDFLAGS'"' >> .envrc
-
+case $config in
+    *wasm*)
+        echo "export WASM_HOME="'"'$WASM_HOME'"'         >> .envrc
+	echo "export EMSDK_QUIET=1"			 >> .envrc
+	echo "source "'$'"WASM_HOME/emsdk/emsdk_env.sh"	 >> .envrc
+esac
 ./configure
